# Generated by Django 4.1.2 on 2026-08-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklistmodel',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
        migrations.AddField(
            model_name='stocklistmodel',
            name='is_void',
            field=models.BooleanField(default=False, verbose_name='Void Label'),
        ),
        migrations.AddField(
            model_name='stocklistmodel',
            name='lot_number',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Lot Number'),
        ),
        migrations.AddField(
            model_name='stocklistmodel',
            name='source_asn_code',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Source ASN Code'),
        ),
        migrations.AddField(
            model_name='stocklistmodel',
            name='void_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Void Reason'),
        ),
        migrations.AddField(
            model_name='stocklistmodel',
            name='void_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Void Time'),
        ),
        migrations.AddField(
            model_name='stocklistmodel',
            name='wip_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='WIP Unique ID'),
        ),
        migrations.AddField(
            model_name='stocklistmodel',
            name='wip_status',
            field=models.IntegerField(choices=[(10, 'Received'), (20, 'Inspected'), (30, 'Put Away'), (40, 'Picking'), (50, 'Picked'), (60, 'Delivered'), (70, 'Used'), (90, 'Void')], default=10, verbose_name='WIP Status'),
        ),
    ]
